### ISSUE TITLE
Ufak Degisiklikler

### ISSUE THREAD

**Issue by OsmanBahadirr** [skylab-kulubu/yildizskylab-panel-frontend#2]
takim liderleri tek kisi olmuyor genelde liste olarak tutulması daha iyi olur
Takımlar ortak proje geliştirebiliyorlar bu yüzden projects'teki teams'i de  liste olarak tutmak daha iyi olabilir 
Projects'te takım lideri olmalı. Liste olarak tutulması daha iyi olur
Event nesnesindeki date ve time'yi tek seferde timestamp olarak tutabilir miyiz?

**Comment by yustyy** [comment]
Proje kapsamı küçültüldü, varolan birçok sayfa kullanılmayacak veya yeniden revize edilecek. Ona uygun bir yapı oluştur, akşam 19.00 da toplantıda konuşalım. Timestamp olarak tutmak mantıklı.

**Comment by yustyy** [comment]
Alınacak aksiyonlar konuşuldu, yazıldığı üzere proje kapsamı küçültüldü ve 1 hafta içerisinde mvp çıkacak.
